### ISSUE TITLE
Adapter Startet nicht

### ISSUE THREAD

**Issue by Peter1980FFM** [nobl/ioBroker.senec#1]
senec.0 | 2020-03-06 19:51:48.527 | error | (29756) Error: Error reading from Senec (IP: 192.168.xxx.xxx). Exiting! (Error: Unknown value in JSON: SETUP_WALLBOX_SERIAL0:st_)
-- | -- | -- | --
senec.0 | 2020-03-06 19:51:48.513 | info | (29756) connected to Senec: 192.168.xxx.XX
senec.0 | 2020-03-06 19:51:48.456 | info | (29756) connecting to Senec: 192.168.xxx.XX
senec.0 | 2020-03-06 19:51:48.423 | info | (29756) starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.senec, node: v10.19.0
senec.0 | 2020-03-06 19:51:43.841 | info | (28939) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
senec.0 | 2020-03-06 19:51:43.840 | info | (28939) terminating
senec.0 | 2020-03-06 19:51:43.839 | info | (28939) cleaned everything up...
senec.0 | 2020-03-06 19:51:43.837 | info | (28939) Got terminate signal TERMINATE_YOURSELF

**Comment by nobl** [comment]
Kurze Rückfrage:
Ist im System eine Wallbox konfiguriert?

Falls ja, bräuchte ich den response des Senec Systems, da ich selbst keine Wallbox habe. 
(Adapter auf Debug stellen - dann die Zeile mit "Body" bitte aus dem Logfile kopieren.)

Das Problem sollte dann relativ schnell zu beheben sein, sobald ich weiß, was genau von Senec an dieser Stelle geliefert wird.

(Alternativ kann man das auch über die Dev-Tools z.b. in Firefox auslesen in der Netzwerkanalyse.)

**Comment by nobl** [comment]
Ich habe eben eine neue Version hochgeladen, die den entspr. Wert "auf Verdacht" ausliest und abspeichert. Damit sollte da eigentlich funktionieren - ob allerdings der Inhalt stimmt, kann ich ohne konkrete Werte nicht sagen.

Bitte über Github updaten und kurzes Feedback. Danke!

(Oder warten, bis ich die 1.0.5 auf npmjs hochlade.)

**Comment by Peter1980FFM** [comment]
Hallo nein habe kein Wallbox.
also mit der jetztigen Version kommt was an
![image](https://user-images.githubusercontent.com/45266139/76149982-d2291700-60a5-11ea-8dc4-ac9dc9f7974c.png)
Senec hat nur das Webinterface Kaputt gemacht mit dem letzten Update
![image](https://user-images.githubusercontent.com/45266139/76149994-f684f380-60a5-11ea-8228-c1772fe24b5b.png)
Hier noch der Debug Log

senec.0 | 2020-03-07 19:01:32.845 | debug | (26186) Body: {"STATISTIC":{"STAT_DAY_E_HOUSE":"VARIABLE_NOT_FOUND","STAT_DAY_E_PV":"VARIABLE_NOT_FOUND","STAT_DAY_BAT_CHARGE":"VARIABLE_NOT_FOUND","STAT_DAY_BAT_DISCHARGE":"VARIABLE_NOT_FOUND","STAT_
-- | -- | -- | --
senec.0 | 2020-03-07 19:01:32.845 | debug | (26186) Response: {"statusCode":200,"body":"{\"STATISTIC\":{\"STAT_DAY_E_HOUSE\":\"VARIABLE_NOT_FOUND\",\"STAT_DAY_E_PV\":\"VARIABLE_NOT_FOUND\",\"STAT_DAY_BAT_CHARGE\":\"VARIABLE_NOT_FOUND\",\"STAT_D
senec.0 | 2020-03-07 19:01:32.844 | debug | (26186) Status: 200


Mein Nachtbar bekommt wohl am 14.4 seinen Senec V3 Hybrid DUO der Interessiert sich Brennend für den Adapter ;-) vielen DANK das du dir die Mühe mit gemacht hast

**Comment by nobl** [comment]
Hmmm ... dann ist das vermutlich abhängig von der Version, die auf der Senec läuft ...
Bei mir kommt aktuell nur die Anzahl der Wallboxes - aber die Serials werden überhaupt nicht geliefert.

Dass sie jetzt aber die Statistik für den Tag rausgenommen haben, ist sehr unerfreulich und hoffentlich nur vorübergehend. Sobald diese wieder geliefert werden, sollten bei Dir die States entspr. angelegt werden.

Können wir kurz mal die Versionsnummern der Anlage abgleichen?
Bei mir:
REVISION MCU: 0712
REVISION NPU-REGS: 03
REVISION NPU-IMAGE: 00
REVISION GUI: 0933
REVISION INV: 0 
REVISION NSP: 0

Auf den Hybrid bin ich auch schon gespannt. Im Moment vermute ich, dass er die gleiche Schnittstelle verwendet und damit ohne größere Probleme auslesbar sein sollte. (Zumindest sieht das auf dem Webinterface so aus.)

**Comment by Peter1980FFM** [comment]
Können wir gerne machen
**REVISION MCU: 0720**
REVISION MCU-BL: 954
REVISION NPU-REGS: 03
REVISION NPU-IMAGE: 00
**REVISION GUI: 0939**
REVISION INV: 0
REVISION NSP: 0 / 0

Beschwerde bei SENEC über die fehlenden Werte läuft bereits ;-)

Es gibt ja eine API in den Speichern diese ist aber Exclusiv für den Jung Visu Pro Server SENEC Edition aber der soll 900 Euro kosten...  Ich hoffe nicht das dieses Werte rauszunehmen ein bewustes Handeln von SENEC war, um Ihre Kooperation mit Jung zu schützen

**Comment by nobl** [comment]
Dann bin ich mal gespannt, wann ich das Update bekomme.
Ich schließe dann mal das Ticket und bereite die nächste Version vor :-)

Weitere Unterhaltung gerne via Forum (ich vermute es war das hm-Forum?).
