### ISSUE TITLE
dapter botte ins Repository aufnehmen lassen

### ISSUE THREAD

**Issue by Apollon77** [nobl/ioBroker.senec#114]
Danke :-)

**Comment by nobl** [comment]
Mach ich demnächst :)
Will noch ein paar Sachen anpassen.

**Comment by DerT94** [comment]
Wurde der Adapter schon aufgenommen?

**Comment by nobl** [comment]
duplicate with #131

**Comment by nobl** [comment]
Habe aktuell einen länger anstehenden größeren Change vorgenommen - ohne den wollte ich ihn nie in stable übernehmen lassen :)
