### ISSUE TITLE
State attribute definition missing

### ISSUE THREAD

**Issue by Apropo1710** [nobl/ioBroker.senec#120]
Seit dem letzten Firmware Update des Speichers hab ich folgende Meldungen im Log

`<html>
<body>

senec.0 | 2022-12-11 05:20:29.093 | info | REPORT_TO_DEV: State attribute definition missing for: STECA.AU2020_VERSION_MISMATCH, Val: 0
-- | -- | -- | --
senec.0 | 2022-12-11 05:20:29.063 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_WGRA_MIN, Val: 5.00
senec.0 | 2022-12-11 05:20:29.063 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_WGRA_MAX, Val: 100.00
senec.0 | 2022-12-11 05:20:29.063 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_WGRA, Val: 16.70
senec.0 | 2022-12-11 05:20:29.062 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWD_VOLTAGE, Val: 253,260
senec.0 | 2022-12-11 05:20:29.062 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWD_VMIN, Val: 235,240
senec.0 | 2022-12-11 05:20:29.061 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWD_VMAX, Val: 255,265
senec.0 | 2022-12-11 05:20:29.061 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWD_PMIN, Val: 100,0
senec.0 | 2022-12-11 05:20:29.059 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWD_PMAX, Val: 100,20
senec.0 | 2022-12-11 05:20:29.059 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWD_PERCENT, Val: 100,20
senec.0 | 2022-12-11 05:20:29.058 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWC_VOLTAGE, Val: 207,215
senec.0 | 2022-12-11 05:20:29.058 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWC_VMIN, Val: 180,180
senec.0 | 2022-12-11 05:20:29.057 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWC_VMAX, Val: 230,230
senec.0 | 2022-12-11 05:20:29.057 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWC_PMIN, Val: 0,100
senec.0 | 2022-12-11 05:20:29.057 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWC_PMAX, Val: 20,100
senec.0 | 2022-12-11 05:20:29.055 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VWC_PERCENT, Val: 20,100
senec.0 | 2022-12-11 05:20:29.054 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VVAR_VOLTAGE, Val: 207,220,240,258
senec.0 | 2022-12-11 05:20:29.053 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VVAR_VMIN, Val: 180,180,230,230
senec.0 | 2022-12-11 05:20:29.053 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VVAR_VMAX, Val: 230,230,265,265
senec.0 | 2022-12-11 05:20:29.052 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VVAR_PMIN, Val: 30,0,0,196
senec.0 | 2022-12-11 05:20:29.052 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VVAR_PMAX, Val: 60,0,0,226
senec.0 | 2022-12-11 05:20:29.051 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VVAR_PERCENT, Val: 44,0,0,196
senec.0 | 2022-12-11 05:20:29.051 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VNOMMAX_RANGE, Val: 258
senec.0 | 2022-12-11 05:20:29.051 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VNOMMAX_MIN, Val: 244
senec.0 | 2022-12-11 05:20:29.050 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_VNOMMAX_MAX, Val: 258
senec.0 | 2022-12-11 05:20:29.050 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_SELECTED_REGION, Val: 0
senec.0 | 2022-12-11 05:20:29.049 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_RESPONSE_MODES, Val: 19
senec.0 | 2022-12-11 05:20:29.049 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_REACTIVEPOWER_MIN, Val: -60.00
senec.0 | 2022-12-11 05:20:29.049 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_REACTIVEPOWER_MAX, Val: 60.00
senec.0 | 2022-12-11 05:20:29.049 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_REACTIVEPOWER, Val: 0
senec.0 | 2022-12-11 05:20:29.048 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_NOT_DEFAULT, Val: 0
senec.0 | 2022-12-11 05:20:29.048 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_HEXPORT_ENABLED, Val: 0
senec.0 | 2022-12-11 05:20:29.048 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_HEXPORT, Val: 0
senec.0 | 2022-12-11 05:20:29.047 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FULCO_MIN, Val: 50.10
senec.0 | 2022-12-11 05:20:29.047 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FULCO_MAX, Val: 50.50
senec.0 | 2022-12-11 05:20:29.046 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FULCO, Val: 50.25
senec.0 | 2022-12-11 05:20:29.046 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FTRANSITION_MIN, Val: 50.50
senec.0 | 2022-12-11 05:20:29.046 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FTRANSITION_MAX, Val: 52.00
senec.0 | 2022-12-11 05:20:29.045 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FTRANSITION, Val: 50.75
senec.0 | 2022-12-11 05:20:29.045 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FSTOPCH_MIN, Val: 48.00
senec.0 | 2022-12-11 05:20:29.045 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FSTOPCH_MAX, Val: 49.50
senec.0 | 2022-12-11 05:20:29.044 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FSTOPCH, Val: 49.00
senec.0 | 2022-12-11 05:20:29.044 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FPMIN_MIN, Val: 51.00
senec.0 | 2022-12-11 05:20:29.043 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FPMIN_MAX, Val: 53.00
senec.0 | 2022-12-11 05:20:29.043 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FPMIN, Val: 52.00
senec.0 | 2022-12-11 05:20:29.042 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FPMAX_MIN, Val: 47.00
senec.0 | 2022-12-11 05:20:29.041 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FPMAX_MAX, Val: 49.00
senec.0 | 2022-12-11 05:20:29.041 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FPMAX, Val: 48.00
senec.0 | 2022-12-11 05:20:29.040 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FLLCO_MIN, Val: 49.50
senec.0 | 2022-12-11 05:20:29.040 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FLLCO_MAX, Val: 49.90
senec.0 | 2022-12-11 05:20:29.040 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FLLCO, Val: 49.75
senec.0 | 2022-12-11 05:20:29.039 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_FIXEDFACTOR, Val: 1.00
senec.0 | 2022-12-11 05:20:29.039 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_COSPHIMODE, Val: 0
senec.0 | 2022-12-11 05:20:29.039 | info | REPORT_TO_DEV: State attribute definition missing for: GRIDCONFIG.AU2020_ACTIVE_REGISTER, Val: 0
senec.0 | 2022-12-11 05:20:28.958 | info | REPORT_TO_DEV: State attribute definition missing for: WIZARD.LOGGER_SEVERITY, Val: 8
senec.0 | 2022-12-11 05:20:28.954 | info | REPORT_TO_DEV: State attribute definition missing for: WIZARD.BATT_IPU_MISMATCH, Val: 0
senec.0 | 2022-12-11 05:20:28.951 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_TARGET_POWER, Val: 0
senec.0 | 2022-12-11 05:20:28.951 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_STARTTIME_MINUTE, Val: 0
senec.0 | 2022-12-11 05:20:28.951 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_STARTTIME_HOUR, Val: 0
senec.0 | 2022-12-11 05:20:28.950 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_LAST_CHANGE_UTC, Val: 0
senec.0 | 2022-12-11 05:20:28.950 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_IS_ACTIVE, Val: 0
senec.0 | 2022-12-11 05:20:28.950 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_IGNORE_COUNTRY_TYPE, Val: 0
senec.0 | 2022-12-11 05:20:28.949 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_EXPORT_LIMIT, Val: 0
senec.0 | 2022-12-11 05:20:28.949 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_ENDTIME_MINUTE, Val: 0
senec.0 | 2022-12-11 05:20:28.946 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_ENDTIME_HOUR, Val: 0
senec.0 | 2022-12-11 05:20:28.945 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_DAILY_PARAMETER_RESET, Val: 1
senec.0 | 2022-12-11 05:20:28.945 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_ACTIVATE_TARGET_POWER, Val: 0
senec.0 | 2022-12-11 05:20:28.944 | info | REPORT_TO_DEV: State attribute definition missing for: ENERGY.VPP_ACTIVATE_EXPORT_LIMIT, Val: 0
senec.0 | 2022-12-11 05:20:28.503 | info | LowPrio polling ...

</body>
</html>`

**Comment by nobl** [comment]
Was hier noch interessant sein könnte:
- Kann man zu einzelnen States sagen, was genau diese darstellen?
- Gilt für einzelne States eine bestimmte Einheit?

**Comment by nobl** [comment]
added and included in next version.

Please check if we can add more descriptive names and maybe units and such.

Pull Requests are welcome.
