### ISSUE TITLE
banned from cloud?

### ISSUE THREAD

**Issue by santiagos5** [nobl/ioBroker.senec#130]
hello, I wanted integrate my SENEC PV with my domotics, so I installed the SENEC plugin for Homebridge and a SENEC plugin for HomeAssistant, because i wanted create rule based on current production and scan interval of both plugin is 60 seconds. 

Then looking for some alternative SENEC app because it show data only every 5 minutes, foud Solectrus and tried it. After some research i found your topic and try also with ioBrokerSenec but i read for the first time **_"If you are polling too often, your SENEC system will not be able to connect to the SENEC servers anymore!"_** so i open my SENEC app and see that no data was showing

if i reset the inverter (botton blue in left side panel) the first 10 minutes show me current data in SENEC app, then nothing more. Maybe 
i'm not not be able to connect to the SENEC servers anymore? and why if i am polling too often, my SENEC system will not be able to connect to the SENEC servers anymore? and there is a way to resolve?

**Comment by nobl** [comment]
You aren't getting banned from the cloud.
The senec appliance is highly sensitive to traffic and will simply stop to communicate with the senec servers and eventually even perform unwanted restarts trying to fix the issue.

If you are polling the system with that many tools you are definitely running into that issue.

That is the reason why this adapter restricts polling in regards to data requested and interval.

I cannot help you with that. But please check your paperwork with senec about having to supply proper internet accessibility for them to honor guarantee and such.

**Comment by santiagos5** [comment]
Thanks, so will I have to change inverter if covered under warranty?
 I don't understand though why the first 10 minutes when turned on, it communicates well with the server and then it stop also if i have unistalled all plugin type at the moment

**Comment by nobl** [comment]
The appliance can only answer so many requests in a given timeframe.
Once you hit that limit the appliance will stop answering requests and it might even reboot eventually.

Depending on the amount of requests it can take so or so long before the timeout happens.
This can be 10 minutes or more or less. Depends.
