### ISSUE TITLE
Consider adding this adapter to the stable repository

### ISSUE THREAD

**Issue by mcm1957** [nobl/ioBroker.senec#131]
Thanks for the work you spent for this adapter

Please consider adding your adapter to the stable repository if no known issues exist.
https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-stable-repository

**Comment by nobl** [comment]
Just added a change I wanted to implement for a while which was important for me to even consider the adapter ready for stable. So lets see if we run into any issues.

**Comment by mcm1957** [comment]
Replaced by #149
