### ISSUE TITLE
iobroker can not install latest senec adapter

### ISSUE THREAD

**Issue by omc69** [nobl/ioBroker.senec#139]
Clean fresh and updated iobroker installation. While adding senec adapter in iobroker console it seems that version 0.01 is getting installed. The config menu looks pretty old compared to the one located in the readme. 

Any help is appreciated. 

![2023-04-01 16 57 36](https://user-images.githubusercontent.com/41850260/229296821-d8ca68f4-7ea6-4727-a570-49186d3c97f1.png)

**Comment by nobl** [comment]
Suppose you got the wrong adapter.
Install via iobroker via interface using "latest" repository.

**Comment by omc69** [comment]
Custom install solved the issue.
