### ISSUE TITLE
Wrong unit for Datapoint senec.0.STATISTIC.LIVE_WB_ENERGY.0 -> Wh instead of kWh

### ISSUE THREAD

**Issue by B4n4n3** [nobl/ioBroker.senec#148]
The unit of the datapoint senec.0.STATISTIC.LIVE_WB_ENERGY.0 (.1; .2; and .3) is watt hours (Wh) instead of kilowatt hours (kWh). 
I was able to check that via the Senec app. 
The data point reflects the total (all time) energy that has flowed through the wall box.

**Comment by nobl** [comment]
fixed with commit https://github.com/nobl/ioBroker.senec/commit/3e5fcc67291b3e75412202054a4bb4818e4f753a
(will be includedin next version)
