### ISSUE TITLE
Grid Today nicht zu finden

### ISSUE THREAD

**Issue by funboxbolzer** [nobl/ioBroker.senec#15]
Hallo,
ich finde die Grids für den Tagesverbrauch nicht.
Soll ja laut Anleitung in ENERGY sein, aber ich finde da leider nichts.

Habe eine SENEC.Home V3 hybrid duo

Danke

**Comment by nobl** [comment]
Senec hat die Tageswerte vor geraumer Zeit entfernt. Diese sind nur noch in älteren Versionsständen der SENEC Teil der API.

Es gibt leider nur drei Möglichkeiten: 
a) Downgrade der Senec (bzw. falls älterer Stand, Auto-Updates abschalten lassen), 
b) das teure System von Jung kaufen (das letztendlich nichts anderes macht als c) ), oder 
c) die Werte selbst berechnen (siehe #6 )

Letztendlich:
Energiewerte am Tagesanfang merken und dann bei jedem Update des entspr. Datenpunkts eine Neuberechnung des Tageswertes durchführen via Script.

**Comment by nobl** [comment]
Update hierzu: https://github.com/nobl/ioBroker.senec/issues/6#issuecomment-830825152
