### ISSUE TITLE
Fehler/Log nach Update auf JS-Controller 3.3.1

### ISSUE THREAD

**Issue by SoldierOc** [nobl/ioBroker.senec#16]
Hallo Zusammen,

nach dem heutigen Update des JS-Controllers + Neustart von IOBroker erhalte ich im LOG (auch nach mehrmaligem Neustart vom Senec Adapter) ím Sekundentakt Warnmeldungen, weil scheinbar der Data Value einen String haben möchte, aber alle Datenpunkte eben Nummern sind.

Könntest du/ihr dies ggf. fixen :)?

Besten Dank

Node.JS: 12.22.1
JS.Controler: 3.3.1
Senec Adapter: 1.1.0

![2021-04-30 09_43_57-logs - ioBroker](https://user-images.githubusercontent.com/63428971/116664483-d8104480-a998-11eb-8d8b-fcf5333f14a3.jpg)

**Comment by nobl** [comment]
Ich habe bei mir 3.3.1 noch nicht drauf - daher kann ichs nicht nachvollziehen.

Aber:
Es kann sein, dass die Datenpunkte in einer früheren Version als "String" angelegt wurden.
Es sollte helfen, diese einfach zu löschen (werden korrekt neu angelegt). Alternativ kann man sie auch editieren und von String auf Number umstellen.

**Comment by SoldierOc** [comment]
Das Problem betrifft wohl sehr viele Adapter. Denke der Fehler sollte nicht (einzeln) bei jedem User gefixt werden, sondern allgemein via Update (bzw. ggf. Neuinstallation des Adapters?)?

Siehe hier:

https://forum.iobroker.net/topic/44624/js-controller-3-3-jetzt-im-latest/30

**Comment by nobl** [comment]
Ich weiß.
Der Adapter hat früher mal (fehlerhaft) mit "String" gearbeitet, was aber ein Fehler war, der behoben wurde.
Alle nicht neu erstellten Datenpunkte sind daher falsch im ioBroker angelegt und müssen geändert werden.
Am schnellsten geht das mit:

- Adapter stoppen
-  Datenpunkte löschen
- Adapter starten

Das Problem tritt jetzt auf, nachdem der JS-Controller umgestellt wurde und das nicht mehr einfach "durchwinkt".

Sprich: Der Adapter hat den Korrekten Datentyp - der Datenpunkt im ioBroker aber nicht :-)

Ich schau mal, ob ich mir da was einfallen lassen kann, sofern ich Zeit dazu finde.

**Comment by nobl** [comment]
es kommt gleich ein Update, das die entspr. veralteten Datenpunkte automatisch korrigiert.
Du könntest das gerne mal direkt von github updaten oder warten, bis das Repo aktualisiert wurde.

**Comment by SoldierOc** [comment]
Kann ich gerne machen. Wird aber vermutlich erst morgen was werden....

By the way: Danke für die ultra-schnelle Reaktion!

**Comment by nobl** [comment]
> Kann ich gerne machen. Wird aber vermutlich erst morgen was werden....
Kein Stress. Release liegt bereit und wird dann eh als Update angeboten.

> By the way: Danke für die ultra-schnelle Reaktion!
Wollte das eh schon länger einbauen, dass Änderungen in den Object-Attributen auch in den bestehenden Objects reflektiert werden. :)

**Comment by SoldierOc** [comment]
So - nun doch etwas schnelleres Feedback :)

Habe via Github auf 1.1.1 eine neu Instanz geupdated. Keine Datenpunkte (vorab) manuell gelöscht.
Problem scheint gelöst - ich erhalte keine Warn-Meldungen mehr!

Danke für den raschen Fix!
