### ISSUE TITLE
Senec changed to https 

### ISSUE THREAD

**Issue by MaBernO** [nobl/ioBroker.senec#164]
Since 17.8. i have no access with the standard port 80 to my senec V2.1 
I noticed some software update from senec.
The web interface is now accessible via the https port (443).
Nothing else seems to have changed.

Can you support this variant in the adapter?

REVISION MCU: 3825

REVISION MCU-BL: 2307

REVISION NPU-REGS: 10

REVISION NPU-IMAGE: 2307

REVISION GUI: 2966

REVISION INV: 660

REVISION NSP: 243 / 243

**Comment by nobl** [comment]
Currently preparing release 1.4.2.
This will have an option to switch to https in settings.

This is currently considered "experimental" because I have no ways to test it. So feedback is appreciated!

This change should not cause issues with systems not supporting https (yet).

**Comment by MaBernO** [comment]
I tried it with 1.4.2 with enabled https option:

2023-08-21 22:39:41.763 | error | Error: Error connecting to Senec (IP: https://192.168.178.247). Exiting! (unable to verify the first certificate). Try to toggle https-mode in settings and check FQDN of SENEC appliance.
-- | -- | --
senec.0 | 2023-08-21 22:39:41.761 | info | unable to verify the first certificate
senec.0 | 2023-08-21 22:39:41.005 | info | connecting to Senec: https://192.168.178.247/lala.cgi

**Comment by MaBernO** [comment]
seems to be a problem with senec's certificate.
Maybe the option NODE_TLS_REJECT_UNAUTHORIZED=0 needs to be passed.

**Comment by nobl** [comment]
can you try to update from github?
I made some changes in main.js - hoping that works :)

or just modify main.js:
right below 'use strict'; add:
`const https = require('https');
const agent = new https.Agent({ rejectUnauthorized: false });`

and around line 133 this `agent,` should be added so it looks like
`doGet(pUrl, pForm, caller, pollingTimeout) {
		return new Promise(function (resolve, reject) {
			axios({
				method: 'post',
				agent,
				url: pUrl,
				data: pForm,
				timeout: pollingTimeout
			})`

**Comment by MaBernO** [comment]
same error again.
I added  process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'; in the adapter init (with 1.4.2) communication with senec was working.

**Comment by nobl** [comment]
yeah - just that pretty much is "kill them all" :)
I would prefer solving that via user-agent settings

**Comment by MaBernO** [comment]
Ok, if you have another proposal i will try it out.

**Comment by nobl** [comment]
Just pushed another update to github - while I cannot test with a senec on https I tried with another machine and it looks promising :)

**Comment by MaBernO** [comment]
1.4.3 is working with https.
Thank you very much.

**Comment by nobl** [comment]
Thanks for reporting of course testing :)
