### ISSUE TITLE
Keine Verbindung mit Gerät oder Dienst 

### ISSUE THREAD

**Issue by raVsu** [nobl/ioBroker.senec#165]
![Screenshot_20230829_214146_Edge](https://github.com/nobl/ioBroker.senec/assets/99563323/1c4f8c87-fcdf-4b2b-a24b-01fd0a7e7e1e)
Hallo, 
heute wurde ein Softwareupdate im Speicher (home V2.1) seitens Senec durchgeführt. Seit dem funktioniert der Adapter nicht richtig. Ist dieser Fehler bereits bekannt? Bis zu dahin hat alles sehr gut funktioniert.

**Comment by MLeo84** [comment]
Selbes Problem hier. Ja, Thema ist bekannt und bereits gelöst: https://github.com/nobl/ioBroker.senec/issues/164
Die Version 1.4.3 beinhaltet auch schon den fix:
![image](https://github.com/nobl/ioBroker.senec/assets/39462358/6f6f805d-17cc-426c-beb2-10e935eb87c9)
Leider kann es wohl etwas dauern bis diese (oder eine höhere) Version im iobroker repository auftaucht.

**Comment by raVsu** [comment]
Supper, danke für die schnelle Antwort 😀

**Comment by MLeo84** [comment]
die jüngste - potentiell fehlerbehaftete - Version kann über diesen Button im Adapter tab installiert werden:
<img width="132" alt="image" src="https://github.com/nobl/ioBroker.senec/assets/39462358/1a9670ea-b2fa-4298-b4b5-c7cf8637f19b">

hier dann "von Github" auswählen und nach senec suchen:
<img width="737" alt="image" src="https://github.com/nobl/ioBroker.senec/assets/39462358/78508101-bc2a-4d59-999a-1bcadb94f15e">
Ich habe das bei mir jetzt gemacht und es läuft wieder alles. Werde berichten wenn mir etwas auffällt.

**Comment by raVsu** [comment]
Danke für den Hinweis. Jetzt läuft es wieder 😀

**Comment by B4n4n3** [comment]
"Verbunden mit Gerät oder Dienst" ist bei mir ebenfalls "rot".
Ich hab aber die aktuelle Version 1.6.10 installiert.
https ist ebenfalls aktiviert.

Hat noch jemand das Problem?

**Comment by nobl** [comment]
Was sagen Log bzw debug mode?

Am 29. Oktober 2023 21:00:04 MEZ schrieb B4n4n3 ***@***.***>:
>"Verbunden mit Gerät oder Dienst" ist bei mir ebenfalls "rot".
>Ich hab aber die aktuelle Version 1.6.10 installiert.
>https ist ebenfalls aktiviert.
>
>Hat noch jemand das Problem?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nobl/ioBroker.senec/issues/165#issuecomment-1784210767
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
