### ISSUE TITLE
Missing statisic in Adapter

### ISSUE THREAD

**Issue by Meteroidn** [nobl/ioBroker.senec#173]
**Describe the bug**  
In the actual Version I miss the statistiscs for consumption delivery and generated an so on

In the Version 1.3.X was the statistisc implimented

**Comment by nobl** [comment]
Removed by SENEC from lala.cgi - so we can no longer supply that. (In fact they removed the whole STATISTICS tree.)
You may wish to direct your complaints to SENEC directly :)

**Comment by Meteroidn** [comment]
Thank you for the Information that is not good from senec
