### ISSUE TITLE
Senec changed from HTTP to HTTPS

### ISSUE THREAD

**Issue by synaps18** [nobl/ioBroker.senec#174]
**Describe the bug**  
Senec Webinterface and API is no longer available over HTTP. They switched over to HTTPS. 

**Screenshots & Logfiles**  
Screenshot is only in german:
![9451e680-fd22-44d6-b177-d8557745bfb6](https://github.com/nobl/ioBroker.senec/assets/80043567/98d82a93-5e4b-4c5d-ada2-3daa87761859)

**Comment by nobl** [comment]
fully covered since 1.4.3 - please update your adapter if you still experience this issue.

**Comment by nobl** [comment]
#164
