### ISSUE TITLE
Texts DE: Wallbox.State

### ISSUE THREAD

**Issue by nobl** [nobl/ioBroker.senec#18]
Taken from  https://github.com/nobl/ioBroker.senec/issues/17#issuecomment-832269625

The "translation" for the datapoints
 senec.0.WALLBOX.STATE.0/1/2/3 (the datapoints are decimal, but the definition is in hex):

0xA1: "Warte auf E-Fahrzeug", (161) 
0xB1: "E-Fahrzeug fragt Ladung an", (177) 
0xB2: "E-Fahrzeug kann geladen werden", (178) 
0xC2: "E-Fahrzeug lädt momentan", (194) 
0xC3: "E-Fahrzeug lädt mit verringertem Strom (Fehler F16, F17)", (195) 
0xC4: "E-Fahrzeug lädt mit verringertem Strom (Schieflast F15)", (196)
0xE0: "Wallbox deaktiviert durch EN1/Schlüsselschalter oder für Konfigurationsupdate", (224)
0xE1: "Test Production", (225) 
0xE2: "Steuereinheit kann programmiert werden", (226)
0xE3: "Warte auf Kommunikation mit SENEC-Speicher", (227) 
0xF1: "Unerwartet geschlossener Kontakt (verschweißt)", (241) 
0xF2: "Interner Fehler", (242) 
0xF3: "DC Fehlerstrom erkannt", (243) 
0xF4: "Fehler Kommunikation", (244) 
0xF5: "Sperren der Ladebuchse fehlgeschlagen", (245) 
0xF6: "Kabelfehler", (246) 
0xF7: "E-Fahrzeug meldet Übertemperatur", (247) 
0xF8: "Kommunikationsfehler zum E-Fahrzeug", (248) 
0xF9: "Überstrom erkannt", (249) 
0xFA: "Temperaturgrenzwert überschritten", (250) 
0xFB: "Unerwartet geöffneter Kontakt", (251) 
0xFC: "Reserved State", (252) 
0xFD: "Reserved State" (253) };

In my case the 0xA1 = 161 = "Warte auf E-Fahrzeug". 

I wrote the decimal values in brackets () behind the definition.

**Comment by noffycws** [comment]
Here are some translations:

English:
0xA1: "Waiting for EV",
    0xB1: "EV is asking for charging",
    0xB2: "EV has the permission to charge",
    0xC2: "EV is charged",
    0xC3: "C2 w. reduced current (error F16, F17)",
    0xC4: "C2 w. reduced current (imbalance F15)",
    0xE0: "Charging point disabled by enable input EN1 / key lock or for update",
    0xE1: "production test",
    0xE2: "EVCC can be programmed",
    0xE3: "Bus idle",
    0xF1: "Unintended closed contact (Welding)",
    0xF2: "Internal error",
    0xF3: "DC residual current detected",
    0xF4: "Upstream communication timeout",
    0xF5: "Lock of socket failed",
    0xF6: "CS out of range",
    0xF7: "State D requested by EV",
    0xF8: "CP out of range",
    0xF9: "Overcurrent detected",
    0xF10: "Temperature outside limits",
    0xF11: "Unintended opened contact",
    0xF12: "Reserved State",
    0xF13: "Reserved State",

Italian:

0xA1: "In attesa di collegamento ad EV",
    0xB1: "Richiesta carica da auto elettrica",
    0xB2: "L'auto elettrica è pronta per la ricarica",
    0xC2: "L'auto elettrica è in carica",
    0xC3: "Carica auto elettrica a corrente ridotta",
    0xC4: "Carica auto elettrica a corrente ridotta",
    0xE0: "Wallbox disattivato dal EN1 / interruttore a chiave o per aggiornamento",
    0xE1: "Test",
    0xE2: "L'unità di controllo può essere programmata",
    0xE3: "Attendere la comunicazione con il sistema di accumulo SENEC",
    0xF1: "Errore: Contatto chiuso (saldato)",
    0xF2: "Errore interno",
    0xF3: "Rilevata corrente di guasto DC",
    0xF4: "Errore connessione",
    0xF5: "Blocco della presa per la ricarica non riuscito",
    0xF6: "Guasto del cavo",
    0xF7: "Segnalazione sovratemperatura",
    0xF8: "Errore di comunicazione con l'auto elettrica",
    0xF9: "Rilevata sovracorrente",
    0xF10: "Errore: Temperature limite superate!",
    0xF11: "Errore: Contatto aperto",
    0xF12: "Reserved State",
    0xF13: "Reserved State",

It seems that there are currently not more languages.

You can access to the languages when opening the following JavaScript:
http://ip/js/DE-de.js
http://ip/js/EN-en.js
http://ip/js/IT-it.js

**Comment by nobl** [comment]
added with next release (cannot test though because I don't have a wallbox).

@noffycws the status for you shows as 161?

**Comment by noffycws** [comment]
Yes. In the datapoint ´senec.0.WALLBOX.STATE.0´ I have the value 161. In the App/SENEC-Website it is shown as "Warte auf E-Fahrzeug".

**Comment by nobl** [comment]
ok. all good then :-)
