### ISSUE TITLE
alltime statistic

### ISSUE THREAD

**Issue by metzger304** [nobl/ioBroker.senec#182]
Unter _api /// Statistic/Alltime werden nur die Daten von 2023 angezeigt?

Ist es möglich die Daten von Installationsbeginn anzeigen zu lassen? 
Werden die Daten der vergangenen Jahre in der API nicht bereitgestellt?

Danke und Grüße

**Comment by nobl** [comment]
Siehe Changelog :)
![grafik](https://github.com/nobl/ioBroker.senec/assets/4102132/be7d841e-4108-4909-8230-6da74bb5be5f)

Haken setzen in den Einstellungen.

![grafik](https://github.com/nobl/ioBroker.senec/assets/4102132/fc0e6dde-e7cc-4602-82c5-3a1002aec965)

**Comment by metzger304** [comment]
vielen Dank hat geklappt!
