### ISSUE TITLE
Warning: (addUserDps) Datapoints config for ENERGY doesn't follow [A-Z0-9_,] (no blanks allowed!) - Ignoring:

### ISSUE THREAD

**Issue by esusxunil** [nobl/ioBroker.senec#183]
**Describe the bug**  
Warning: (addUserDps) Datapoints config for ENERGY doesn't follow [A-Z0-9_,] (no blanks allowed!) - Ignoring:

**To Reproduce**  
Start the Adapter
Go to Protocols
Find the Warning

**Expected behavior**  
No Warnings

**Screenshots & Logfiles**  
![image](https://github.com/nobl/ioBroker.senec/assets/61476952/a78ebc8c-c9fb-43f7-a562-f92cd903304f)

**Versions:**  
 - Adapter version: 1.6.5
 - JS-Controller version: <js-controller-version> 5.0.12
 - Node version: 18.17.1
 - Operating system: Docker

**Additional context**  
It looks like all previous data under _calc are currently missing, I hoped to find the missing statistics (about today, power consumed, produced...) somewhere else and found that error message.

**Comment by nobl** [comment]
Bitte korrigiere deine Settings im Bereich "HighPrio Polling".
Du hast hier wohl individuelle Einstellungen vorgenommen und im Energy-Bereich steht kein Wert, bzw. nur ein Leerzeichen drin, aber der Haken ist dennoch gesetzt.

Die Nutzung dieses Config-Bereichs macht nur Sinn, unter speziellen Anforderungen und natürlich sollte nur aktiviert werden, was auch benötigt wird und sinnvoll konfiguriert wurde :)
Daher auch einfach das "Warning", dass der Benutzer hier nicht verwertbare Daten hinterlegt hat :)

Ansonsten: _calc wird nichts mehr berechnen, wenn die Maschine schon von Senec aktualisiert wurde. Die dafür notwendigen Datenpunkte werden nicht länger über die lala.cgi geliefert (Statistic-Zweig). Nebenbei wurden auch noch andere Informationen aus seitenes Senec entfernt.

Alternativen dazu kann man über die Nutzung der API erhalten.

Den _calc-Zweig kannst du theoretisch löschen und er sollte auch nicht mehr erscheinen.
Allerdings verlierst du dann auch möglicherweise gesicherte Statistikdaten dazu.

**Comment by esusxunil** [comment]
Scheint der Fehler gewesen zu sein. Die fehlenden Datenpunkte habe ich jetzt ueber die API bekommen. Vielen Dank fuer die Antwort (und den Adapter generell...)
