### ISSUE TITLE
Force load switch object stopped working

### ISSUE THREAD

**Issue by Kirmesboxer24** [nobl/ioBroker.senec#192]
The "force load" functionality seems not to work anymore. Got a script which triggered it overnight, which worked. But the battery didn’t charge at all. 
Manually switching it does nothing as well. 

The functionality on the device's webserver is still functional. 
![Bildschirmfoto 2023-10-19 um 08 14 31](https://github.com/nobl/ioBroker.senec/assets/56580927/8eb277d1-8731-43ea-8c15-3181ea09d2b2)

**Comment by Kirmesboxer24** [comment]
Found the new switch in the config, which enables control. Wasn’t there when I initially tested the feature. Sorry for bothering you...

**Comment by nobl** [comment]
Still working. But any kind of "Batteriecheck" or like that stops it. Check by logging the status under energy 


Am 19. Oktober 2023 08:18:31 MESZ schrieb Kirmesboxer24 ***@***.***>:
>The "force load" functionality seems not to work anymore. Got a script which triggered it overnight, which worked. But the battery didn’t charge at all. 
>Manually switching it does nothing as well. 
>
>The functionality on the devices webserver is still fuuctional. 
>![Bildschirmfoto 2023-10-19 um 08 14 31](https://github.com/nobl/ioBroker.senec/assets/56580927/8eb277d1-8731-43ea-8c15-3181ea09d2b2)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nobl/ioBroker.senec/issues/192
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by nobl** [comment]
Ah yes. Well - sort of had to add that extra step just in case.
Should be mentioned in changelog though. :)


Am 19. Oktober 2023 08:23:12 MESZ schrieb Kirmesboxer24 ***@***.***>:
>Found the new switch in the config, which enables control. Wasn’t there when I initially tested the feature. Sorry for bothering you...
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nobl/ioBroker.senec/issues/192#issuecomment-1770138939
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
