### ISSUE TITLE
STATISTICS Folder missing

### ISSUE THREAD

**Issue by Hobbyflyer** [nobl/ioBroker.senec#193]
**Describe the bug**  
With latest adapter and FW (V3 Duo) values for LIVE Grid Import / Export are missing.

**To Reproduce**  
Update Adapter and FW Senec to latest

**Expected behavior**  
Values in Statistics 

**Versions:**  
Plattform: linux
Betriebssystem: Ubuntu 22.04 LTS (lxc proxmox)
Architektur: x64
CPUs: 2
Geschwindigkeit: 3135 MHz
Modell: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
RAM: 4 GB
Node.js: v18.17.1
NPM: 9.6.7
JS 7.1.4

**Comment by Hobbyflyer** [comment]
Maybe Senec FW Problem?

**Comment by nobl** [comment]
Removed by Senec. There is no Statistic branch anymore (along with others).
You can get similar values via AppAPI integration.

Also see: https://github.com/nobl/ioBroker.senec/blob/master/README.md#166-nobl

**Comment by Hobbyflyer** [comment]
Thanks for reply. GUI_GRID are actual values. Used statistic for source analytics ...will try API
