### ISSUE TITLE
AllTime values are no longer up to date

### ISSUE THREAD

**Issue by erik-schulze** [nobl/ioBroker.senec#194]
There is a bug in main.js, line 562, where all AllTime values are not updated since release v1.6.9
It is the following line of the async function `insertAllTimeHistory(system, key, year, value, einheit)`:
`if (!isNaN(year) || !isNaN(value)) return; // Security fix`

If this line is commented out, there are no issues with updating these values.

**Comment by nobl** [comment]
Ouch - that was a stupid bug.
Fixed in 1.9.10

**Comment by erik-schulze** [comment]
Works now, thank you!
