### ISSUE TITLE
Senec Home 4 / Senec APP API

### ISSUE THREAD

**Issue by oakdesign** [nobl/ioBroker.senec#201]
I have documented most of the Services that are used by the latest Senec APP here:
https://documenter.getpostman.com/view/932140/2s9YXib2td

As I personally use Homeassistant and Node-Red just wanted to supply with the currently available Web API Endpoints as of APP version 4.3.3 (Okt 23), as I have seen that you are using app-gateway back from the APP version 3.12.0 from June 2020 which is outdated and unclear how long it's still maintained by Senec

**Comment by nobl** [comment]
Thanks for the headsup.
Do they indeed mit v1 and v2?
(Like login/systems is calling v1 and others are calling v2 and v1 as fallback?)

**Comment by oakdesign** [comment]
@nobl yes they mix it. Most static Services only have a v1 endpoint. Main Differenzen is in the dynamic Services such as measurement. Where only v1 returns the totals in v2 totals always return null

**Comment by michiproep** [comment]
I created an [SenecHome4 adapter](https://github.com/michiproep/ioBroker.senec-home-4).
It actually runs within my dev-server but I have no clou how to deal with all the github pipelines and release workflows.
Can someone help me out?

![grafik](https://github.com/nobl/ioBroker.senec/assets/12296115/367d6532-f9a5-41b6-a7ad-fbe42621cb93)

**Comment by nobl** [comment]
You are aware that THIS adapter works for the V4?
Why have another adapter?

**Comment by michiproep** [comment]
I don't see how this can work?
After installation, this is the AdminUI:
![grafik](https://github.com/nobl/ioBroker.senec/assets/12296115/eee58db8-dbe5-4cbf-a947-3bcc0df3c2e3)

There is no email/password login. And it does require an IP, so I guess it is connecting locally to the senec device.
But my homeV4 does not have a lala.cgi at all.

Or is there a way which I don't see?

**Comment by nobl** [comment]
Check your version!
![grafik](https://github.com/nobl/ioBroker.senec/assets/4102132/608c38a6-0608-4bc7-a3be-cc708e36b354)

No idea how you could install such an old version :)
That one is YEARS old ...
![grafik](https://github.com/nobl/ioBroker.senec/assets/4102132/b7a44f3f-1bb0-4bbc-8543-713a20f4a97e)

**Comment by michiproep** [comment]
Yes, you are correct. Just checked. Thanks.

BTW, a polling interval of 10 sec should be allowed. I tested with my adapter. I get new values every 20 to 30 seconds

**Comment by nobl** [comment]
The App API only updates values every 5 Minutes - so 10 seconds will only make senec block our requests for good.
I had  intense talks with SENEC in the past - so I have my reasons for doing or not doing certain things :)

**Comment by michiproep** [comment]
Alright. Understood.
Sorry for the confusion!
