### ISSUE TITLE
Alltime Statistik wird nicht aktualisiert

### ISSUE THREAD

**Issue by metzger304** [nobl/ioBroker.senec#208]
Alltime Statistik PV Generation u.a wurde seit 8 Tagen nicht aktualisiert

**Comment by nobl** [comment]
Kann ich so nicht bestätigen - alle Werte wurden innerhalb der letzten 48 Stunden aktualisiert bei mir.

Auch gibt es keinen Wert "PV Generation"?!
![grafik](https://github.com/nobl/ioBroker.senec/assets/4102132/a32a9de9-310d-4bb5-ade8-3958be5ed2ed)

**Comment by nobl** [comment]
Hast du ggf. vor einer Woche Version 1.6.11 eingespielt?
Da haben sich die Datenpunkte geändert (andere Bezeichner).

**Comment by metzger304** [comment]
> Hast du ggf. vor einer Woche Version 1.6.11 eingespielt? Da haben sich die Datenpunkte geändert (andere Bezeichner).

Danke für den Hinweis.
Die neuen Datenpunkte sind mir leider nicht aufgefallen.

Habe nun nochmals den Gesamtverbrauch neu berechnen lassen.
Scheint zu stimmen.

Werden eigentlich bei einem Update, die nicht mehr verwendeten Datenpunkte entfernt?

**Comment by nobl** [comment]
Nein - alte Datenpunkte werden nicht automatisch gelöscht.
Falls da bei jemandem irgendwelche Aktionen dranhängen, hätte das möglicherweise ungeahnte Nebenwirkungen.

Um alle "Altlasten" los zu werden, könnte man den Adapter stoppen und dann alle vorhandenen Datenpunkte einmal löschen. Dann sind aber natürlich auch alle Altdaten weg.
