### ISSUE TITLE
change priority of data point

### ISSUE THREAD

**Issue by mef18** [nobl/ioBroker.senec#21]
I would like to change the priority of one data point to high. I do not want to,change the polling intervall for low priority data. Is this possibel?

**Comment by nobl** [comment]
So far this can only be done via code changes.
I will see if I can find a way so it is possible to add specific DPs to high prio.

Just - as usual - fair warning: Requesting too much information from the SENEC in a given timeframe will make it stop communicating with the senec servers AND also lead to involuntary restarts.

**Comment by ledermann** [comment]
@nobl Out of curiosity, I would like to ask where this information comes from, that too many requests will bring the SENEC device to its knees.

I am the developer of @solectrus and have written a special [SENEC collector](https://github.com/solectrus/senec-collector) that has been polling my SENEC.Home V3 device every 5 seconds for over two years without any issues. I have never heard of any problems from other users either.

Regarding prioritization, I would suggest that the following values be considered high priority:

```ruby
{
  STATISTIC: {
    CURRENT_STATE: '', 
    MEASURE_TIME: ''
  },
  TEMPMEASURE: {
    CASE_TEMP: ''
  }
}
```

**Comment by nobl** [comment]
This is out of experience from many users. If a certain machine doesn't fail upon high-frequency-polling with much data involved this more or less is "luck".

**Comment by nobl** [comment]
Will be possible with v1.5.
