### ISSUE TITLE
senec adapter nicht in adapter liste

### ISSUE THREAD

**Issue by grogo08** [nobl/ioBroker.senec#22]
Hallo zusammen,

 leider finde ich den Adapter senec nicht in meiner Adapter Liste im Iobroker. Gestern schon iobroker update gemacht. Hat leider nicht geholfen.

Es wird bestimmt nur eine Kleinigkeit sein, kann mir jemand helfen.

Danke

**Comment by nobl** [comment]
Adapter is available via **"latest" repository**. You will need to change that in settings.
