### ISSUE TITLE
Cannot find js-controller

### ISSUE THREAD

**Issue by wilsonsgro** [nobl/ioBroker.senec#221]
**Describe the bug**  

On console after run this command **node main**
>  Cannot find js-controller

On console after run this command **iobroker -v**
>  bash: iobroker: command not found

**Versions:**  
 - Adapter version:   ??
 - JS-Controller version:??
 - Node version: v21.6.1
 - Operating system: Debian GNU/Linux 12 (docker)

**Screenshot**  

<img width="516" alt="Screenshot 2024-02-01 alle 22 36 29" src="https://github.com/nobl/ioBroker.senec/assets/12607509/a2486a9e-5249-42c3-99f2-69139842d798">

**Comment by nobl** [comment]
I don't see where this is an adapter problem.
Please use iobroker to install and run this adapter.

**Comment by wilsonsgro** [comment]
thank you for your reply

i run my docker-compose

<img width="447" alt="Screenshot 2024-02-02 alle 10 46 47" src="https://github.com/nobl/ioBroker.senec/assets/12607509/fd02f834-9a4e-405c-a610-fe613bc6deae">

after that enter into container iobrocker

 run install 
> npm i iobroker.senec

go to browser

<img width="624" alt="Screenshot 2024-02-02 alle 10 43 25" src="https://github.com/nobl/ioBroker.senec/assets/12607509/769690b8-9a5d-44b8-97d0-5c407b73eb65">

add adpter

Go to home

run senec

<img width="1678" alt="Screenshot 2024-02-02 alle 10 43 37" src="https://github.com/nobl/ioBroker.senec/assets/12607509/852c6e3e-bea4-4b0c-9797-75aa5757d17d">

but after :

<img width="1460" alt="Screenshot 2024-02-02 alle 10 40 31" src="https://github.com/nobl/ioBroker.senec/assets/12607509/d75fed2f-ef05-4cff-b5b9-ba5e81855e93">

File index.html not found

**where I go wrong?**
