### ISSUE TITLE
Instanz taucht nicht auf - Fehler in Installation?

### ISSUE THREAD

**Issue by Nemo3006** [nobl/ioBroker.senec#223]
Hallo! 
Ich versuche verzweifelt den Adapter zu ioBroker hinzuzufügen. Er installiert auch was aber unter den Instanzen taucht SENEC nicht auf. In den Objekten ist ein Ordner „Senec“ , aber dieser ist leer. Ich weiß gerade keinen Rat mehr. Anbei mal, was mir gemeldet wird: $ iobroker url nobl/ioBroker.senec --host ioBroker --debug
install nobl/ioBroker.senec
NPM version: 10.2.4Installing nobl/ioBroker.senec... (System call)
up to date in 9s133 packages are looking for funding run `npm fund` for details
upload [1] senec.admin /opt/iobroker/node_modules/iobroker.senec/admin/jsonConfig.json jsonConfig.json application/json
upload [0] senec.admin /opt/iobroker/node_modules/iobroker.senec/admin/senec.png senec.png image/png
Process exited with code 0

Kann mir jemand bitte helfen? 
Danke und viele Grüße

**Comment by nobl** [comment]
Du installierst den Adapter (über das UI von iobroker) und danach fügst du über das UI eine Instanz hinzu und konfiguriert diese.

Das wurde korrekt durchgeführt?


Am 25. Februar 2024 22:32:48 MEZ schrieb Nemo3006 ***@***.***>:
>Hallo! 
>Ich versuche verzweifelt den Adapter zu ioBroker hinzuzufügen. Er installiert auch was aber unter den Instanzen taucht SENEC nicht auf. In den Objekten ist ein Ordner „Senec“ , aber dieser ist leer. Ich weiß gerade keinen Rat mehr. Anbei mal, was mir gemeldet wird: $ iobroker url nobl/ioBroker.senec --host ioBroker --debug
>install nobl/ioBroker.senec
>NPM version: 10.2.4Installing nobl/ioBroker.senec... (System call)
>up to date in 9s133 packages are looking for funding run `npm fund` for details
>upload [1] senec.admin /opt/iobroker/node_modules/iobroker.senec/admin/jsonConfig.json jsonConfig.json application/json
>upload [0] senec.admin /opt/iobroker/node_modules/iobroker.senec/admin/senec.png senec.png image/png
>Process exited with code 0
>
>Kann mir jemand bitte helfen? 
>Danke und viele Grüße
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nobl/ioBroker.senec/issues/223
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Nemo3006** [comment]
Der Adapter tauchte im UI nicht auf und ich musste den Umweg über GitHub und die Katze gehen. Plötzlich ging es dann doch. Keine Ahnugn woran das nun lag. Ich habe über 2 Stunden rumprobiert und kaum hast du geantwortet ging es dann. Danke dir trotzdem!
