### ISSUE TITLE
Senec Status is being reported as "unknown" - in local web dashboard it shows "Aufwachladung"

### ISSUE THREAD

**Issue by MLeo84** [nobl/ioBroker.senec#230]
I'm consuming the value in senec.0.ENERGY.STAT_STATE_Text and it is being reported as "unknown"
In the local web dashboard of Senec I see the text "Aufwachladung" - it seems this is something new?

**Comment by nobl** [comment]
Yes that one is new. 
Do you also have the numeric value, per chance?

Am 5. März 2024 15:27:07 MEZ schrieb MLeo84 ***@***.***>:
>I'm consuming the value in senec.0.ENERGY.STAT_STATE_Text and it is being reported as "unknown"
>In the local web dashboard of Senec I see the text "Aufwachladung" - it seems this is something new?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nobl/ioBroker.senec/issues/230
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by marq24** [comment]
@nobl 
Senec device returning a new status '99' (with the latest firmware update)
99: "AUFWACHLADUNG" | "WAKE UP CHARGING" | "CARICA DI RISVEGLIO"
