### ISSUE TITLE
Api All Time Statistik Werte stimmen nicht mit mein-senec überein

### ISSUE THREAD

**Issue by patricknitsch** [nobl/ioBroker.senec#231]
Hi,

die Werte in der All Time Statistik stimmen nicht überein. Nach Prüfung der anderen Statistiken ist dies die einzige Statistik, die nicht passt.

Als Beispiel wird hier folgende Werte angegeben:

generation der Wert 1689 kWh -> mein-senec 35.381,13 kWh
gridConsumption der Wert 3123 kWh -> mein-senec 13.745,62 kWh
gridFeedIn der Wert 384 kWh -> mein-senec 23.279,64 kWh.

Eigentlich sollte doch All Time die gesamten Werte ab Start der Anlage anzeigen, oder?

**Comment by nobl** [comment]
Nur, wenn du einmal eine vollständige Neuberechnung veranlasst hast. 
Dazu gibt es in den Einstellungen sehen Haken.


Am 14. März 2024 20:38:03 MEZ schrieb patricknitsch ***@***.***>:
>Hi,
>
>die Werte in der All Time Statistik stimmen nicht überein. Nach Prüfung der anderen Statistiken ist dies die einzige Statistik, die nicht passt.
>
>Als Beispiel wird hier folgende Werte angegeben:
>
>generation der Wert 1689 kWh -> mein-senec 35.381,13 kWh
>gridConsumption der Wert 3123 kWh -> mein-senec 13.745,62 kWh
>gridFeedIn der Wert 384 kWh -> mein-senec 23.279,64 kWh.
>
>Eigentlich sollte doch All Time die gesamten Werte ab Start der Anlage anzeigen, oder?
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nobl/ioBroker.senec/issues/231
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by patricknitsch** [comment]
Wer lesen kann, ist im Vorteil :) 
Hat geklappt, danke.

**Comment by nobl** [comment]
Ich will nicht jedesmal die gesamte Historie abrufen :)


Am 14. März 2024 21:51:26 MEZ schrieb patricknitsch ***@***.***>:
>Wer lesen kann, ist im Vorteil :) 
>Hat geklappt, danke.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nobl/ioBroker.senec/issues/231#issuecomment-1998463337
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
