### ISSUE TITLE
Entladen Freigeben

### ISSUE THREAD

**Issue by Dette70** [nobl/ioBroker.senec#239]
Vielen Dank für die Bereitstellung und Weiterentwicklung dieses tollen Adapters.

Über senec.0.control.ForceLoadBattery gibt es ja bereits die Möglichkeit, das "Zwangsladen" des Speichers anzustoßen.
Um diese Funktion aber wirklich nutzen zu können, sprich den Speicher danach wieder entladen zu können, muss nach meinem Verständnis den Button "Entladen freigeben" gedrückt werden.

Daher wäre hier die Frage, ob man diese Funktion als zweiten DP unter Control mit einfügen kann. Hier wird die Funktion beschrieben.
[https://gist.github.com/ledermann/d03247fdc0dec5ef7e21d1d352f9fc94](url)

Vielen Dank im Vorab.

**Comment by nobl** [comment]
Nein - das ist nicht der Zweck der Funktion.
Der Datenpunkt kennt "true" und "false".
Solange er true ist, ist die Sicherheitsladung aktiv - wird er false, dann kehrt das System in den Normalzustand zurück.

Ich habe zB ein Script, das zu gewissen Zeitpunkten prüft, ob die die Sicherheitsladung aktiv ist (oder nicht) und sie dann ein/aus schaltet.

![grafik](https://github.com/nobl/ioBroker.senec/assets/4102132/3ebd1d6a-e4fd-4ac4-ae92-54a58c2e5d16)

**Comment by Kirmesboxer24** [comment]
> > Nein - das ist nicht der Zweck der Funktion. Der Datenpunkt kennt "true" und "false". Solange er true ist, ist die Sicherheitsladung aktiv - wird er false, dann kehrt das System in den Normalzustand zurück.
> > Ich habe zB ein Script, das zu gewissen Zeitpunkten prüft, ob die die Sicherheitsladung aktiv ist (oder nicht) und sie dann ein/aus schaltet.
> > ![grafik](https://private-user-images.githubusercontent.com/4102132/331228007-3ebd1d6a-e4fd-4ac4-ae92-54a58c2e5d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Njc0MjUsIm5iZiI6MTcxNTg2NzEyNSwicGF0aCI6Ii80MTAyMTMyLzMzMTIyODAwNy0zZWJkMWQ2YS1lNGZkLTRhYzQtYWU5Mi01NGE1OGMyZTVkMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTM0NTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NkYjE1OTNlM2VlYzA0NjJhYzZhZWFhYzA3YTZkN2E1ZGFjZTI3ZTZjOTZjYWRmOGMwNzZlYzA5ZjlkNTQwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JoPpmmRWZbyNwM-fg_nS3Vm4wUkabQnraOqJLKqE04w)
> > Das ganze habe ich doppelt - für den aktuellen und nächsten Tag und stelle dann immmer Nachmittags die Ladezeiten für den Folgetag ein.
> > Natürlich kann man das auch anders Steuern - zB über den Tibber Adapter, der einen Datenpunkt für "günstige Energie" hat.
> 
> Danke für die schnelle Antwort.
> 
> Dann muss ich mal anders fragen: Wie kann ich den Speicher triggern, dass er die Ladung **gezielt** freigibt?
> 
> Ich möchte ja nicht, dass er sich Nachts mit günstigem Strom lädt und diesen dann sofort wieder abgibt, wenn er voll geladen ist, sondern erst zu einem Zeitpunkt, den ich festlege (Strom am teuersten). So meine Denkweise ...
> 
> Wahrschenlich gibt das die API nicht her, oder? Was kann man denn mit dem Button "Entladen freigeben" sonst steuern?

Solange der Schalter auf "true" steht, wird nicht entladen. Wenn der Akku voll ist, wird also auch der dann verbrauchte Strom aus dem Netz bezogen. Erst wenn der Schalter den Wert "false" hat, wird auch entladen. 
Heisst: Wenn du beispielsweise nachts günstigen Börsenstrom lädst und das abhängig vom Preis steuerst, wird zur "billigen" Zeit sämtlicher Strom, auch jener der abseits der Batterieladung verbraucht wird, aus dem Netz bezogen. Ist die Batterie voll, wird in dieser Stellung nie entladen sondern weiter aus dem Netz verbraucht. Wird der Schalter zur "teuren" Zeit wieder angeknipst, wird entladen. 
Was noch fehlt, ist eine Funktion "Ladung halten" für mittlere Preislagen und wenn der Akku bis zur Preisspitze am Tag nicht halten würde. Aber diese Funktion fehlt bereits in der Senec-Software, folglich kann der Adapter das nicht leisten.

**Comment by nobl** [comment]
Korreklt.
Es gab früher in der Senec noch zwei weitere Funktionen ...
Enladen Sperren und Entladen Freigeben

Das wurde von Senec vermutlich nicht ohne Grund entfernt.

**Comment by Dette70** [comment]
Guten Morgen, mit der Erklärung habt ihr mir sehr geholfen, somit ist das Thgema erledigt, Danke
