### ISSUE TITLE
Senec-Backup-Pro

### ISSUE THREAD

**Issue by Si-Ska** [nobl/ioBroker.senec#24]
Hallo und danke erstmal für diesen Adapter.

Ich habe seid heute endlich das Senec-Backup-Pro Paket in meinem V3 Speicher.  Das ermöglicht mir (über das Senec-Portal und die App), eine Mindestkapazität des Speichers für die Notstromversorgung zu bestimmen.
Diese Einstellung würde ich gerne automatisieren.
Warum? 
In der Winterzeit wird die volle Kapazität des Speichers eher selten ausgenutzt, da nicht genug Energie vom Dach kommt. Hier würde ich die Notstrom-Reserve erhöhen. In der Übergangszeit wird der Speicher fast jeden Tag voll ausgenutzt, hier soll die Notstromreserve so gering wie möglich sein. Im Sommer dagegen ist das völlig egal, weil der Speicher eh nie leer wird.
Eine weitere Überlegung wäre, vor einem drohenden Unwetter die Notstromreserve (rechtzeitig) zu erhöhen, da dann das Risiko eines Stromausfalls besonders hoch ist.

Der Adapter liefert mir den Datenpunkt, der diese Reserve abbildet (Senec.0.BAT1.SPARE_CAPACITY). Leider ist dieser Datenpunkt aber nicht beschreibbar.
Ich denke, das Senec die Parametrierung sehr einschränkt, aber dieser Datenpunkt ist ja eigentlich für eine "manuelle" Veränderung vorgesehen.

Darum meine Frage, ob das in dem Adapter angepasst werden könnte?

Danke für deine Mühe edel

**Comment by Apollon77** [comment]
Ich denke diese Werte sind nur per Cloud änderbar, oder? Wenn ja dann müsste man den Cloud Login bauen und darüber dann "setzen"

**Comment by nobl** [comment]
Nochmal zur Notstromfunktionalität:
Soweit ich die Anlage kenne, ist die Notstromfunktionalität doch ohnehin nur über einen separaten Ausgang (Steckdose) realisiert, da ansonsten eine Trenneinrichtung zum öffentlichen Netz gewährleistet sein müsste.

Grundsätzlich möchte ich persönlich inzwischen jedoch gerne Abstand davon nehmen, eine im Adapter integrierte Funktion bereitzustellen, die irgendetwas außer "Lesen" mit dem Speicher tut.
(Es gibt aber Möglichkeiten, die Schnittstelle schreibend anzusprechen - das möchte ich jedoch nicht öffentlich diskutieren. Alleine schon aus Haftungsgründen.)

**Comment by max-horvath** [comment]
Aber es geht doch auch gar nicht darum, dass auf den Speicher schreibend zugegriffen werden soll. Das würde ich auch nicht befürworten. Wenn man allerdings das Login auf Mein SENEC einbauen würde, dann würde man den "offiziellen" Weg gehen und das Backend von SENEC würde den Speicher passende Werte senden, ohne dass Du Dir als Entwickler Sorgen machen müsstest, ob Du etwas ungetestetes bzw. so nicht vorgesehen Funktionalität ansteuern würdest.

**Comment by nobl** [comment]
cannot be discussed in public.
