### ISSUE TITLE
Connection to API not possible

### ISSUE THREAD

**Issue by mkn1981** [nobl/ioBroker.senec#248]
**instance can't connect to senec api**
Do you have any ideas?
**Log:**
```
2024-07-18 01:19:16.559 | error | Error reading from Senec AppAPI. Retried 10 times. Giving up now. Check config and restart adapter. (400)
-- | -- | --
senec.0 | 2024-07-18 01:19:16.551 | warn | (Poll) received error 400 response from SENEC with content: "HTTP 500 "
```

I already checked config but don't know, what I could do. Problem exists since 9 days. No settings were changed by me. 
(don't know exactly if I maybe updated nodejs...)

Would be great if you could help.
Best, Matze

**Comment by nobl** [comment]
Current version installed?
Userid, password correct?

Try running with debug and see if log provides more information

**Comment by mkn1981** [comment]
for some reason, the does not occur anymore. I changed to debug - but after that, the instance did not lose the connection anymore. I didn't change anything. crazy. I restarted the instance before several times... don't know, what went wrong. But now it works. Sorry for the inconvenience and thank you for your work!!!

**Comment by mkn1981** [comment]
erledgit
