### ISSUE TITLE
Wrong Values with 1.6.13

### ISSUE THREAD

**Issue by COMHOME** [nobl/ioBroker.senec#259]
After updating from 1.6.12 to 1.6.13 the production values are way too high, gui_inverter_power showed like 14000w, even the device has a maximum output of 10000w... after reverting back to 1.6.12, everything is fine again.

Hardware: SENEC HOME V2.1 with 10kw Storage (with external Kostal inverter)

**Comment by nobl** [comment]
should be fixed within the hour. Sorry.

**Comment by nobl** [comment]
Fixed with v1.6.14.
Checks and autodeplyment in progress. Once completed you can either wait for NPM to supply the version or update via iobroker using Github.
