### ISSUE TITLE
Missing Daily Statistic

### ISSUE THREAD

**Issue by B4n4n3** [nobl/ioBroker.senec#4]
I cant find some "daily" statistic for example "STAT_DAY_BAT_CHARGE" in the STATISTIC Channel.
Its possible to fix that?

**Comment by nobl** [comment]
Please also see issue #2 .

Was removed by Senec for "political reasons" (their words) in favour of the system they offer together with Jung. 

You could try to make them downgrade software version on your machine or just live with it. Sorry.

**Comment by nobl** [comment]
Update: https://github.com/nobl/ioBroker.senec/issues/6#issuecomment-830825152
