### ISSUE TITLE
New status 97/

### ISSUE THREAD

**Issue by Signum** [nobl/ioBroker.senec#61]
Apparently SENEC has introduced a new ENERGY.STAT_STATE 97. The Senec "Home V2.1 1ph / Lithium" system shows "Sicherheitsentladung". Apparently this is a new state that was freshly introduced. As you may be aware SENEC has remotely shut down all systems following a series of accidents. So this is a state that is now shown apparently in the course of restarting the systems.

**Comment by noffycws** [comment]
There are some other ne states in case of the security shutdown of SENEC. My list so far (in German / v3 hybrid duo):

95: "BATTERIEDIAGNOSE"
96: "BATTERIE BALANCIERUNG"

Unfortunatetly SENEC does not provide the states on the local webpage (http://IP), so it is a try and error and check the log and the value of the ENERGY.STAT_STATE variable.

Are there other data points which can be interesting in case of the security shutdown? Is there a value of the maximum battery percentage e.g? Currently it is limited to 30% for me.

**Comment by nobl** [comment]
added with #75

**Comment by nobl** [comment]
> Are there other data points which can be interesting in case of the security shutdown? Is there a value of the maximum battery percentage e.g? Currently it is limited to 30% for me.

the most important states that senec appears to use for diagnosis and decision making are added with #75, too
