### ISSUE TITLE
V3 Hybrid Duo MPP Tracker auslesen

### ISSUE THREAD

**Issue by oneill2612** [nobl/ioBroker.senec#7]
Hey 
erstmal vielen danl für den Adapter der macht seine Arbeit soweit ganz gut . Ich habe den V3 Hybrid Duo dieser hat 3 MPP Tracker. Diese lese ich gerade über ein Externes Programm aus wäre es noch möglich diese in den Adapter hinzuzufügen damit ich diese im ioBrocker auslesen kann ?

**Comment by nobl** [comment]
Sollte unter PV1.MPP_INT[0..3] verfügbar sein.
Mit Version 1.0.10 werden diese Werte auf mit hoher Priorität ausgelesen.
(Je nach Stand der Senec GUI werden die Werte übrigens nicht mehr im lokalen Monitoring angezeigt.)

**Comment by oneill2612** [comment]
Ja perfekt jetzt wird es angezeigt . Ich bin happy ich habe eine Nord Ost Ausrichtung und Süd West und wollte immer mal wissen was genau wo ankommt . 

Also hat das Update geklappt . Empfehle es aufjedenfall weiter 

![73AE7245-7846-4406-8387-4AF7191BABB3](https://user-images.githubusercontent.com/70425796/91994362-ceb1d800-ed36-11ea-9b49-b04fc40dad71.png)


J
![60E48F2B-9381-4707-9559-BA587A160CF2](https://user-images.githubusercontent.com/70425796/91994371-d1143200-ed36-11ea-8c4b-330ef3ee886a.jpeg)a
