### ISSUE TITLE
update STAT_STATE_text

### ISSUE THREAD

**Issue by metzger304** [nobl/ioBroker.senec#83]
sw updates by senec creates new  STAT_STATE_text, please update them
see below an example: Batteriediagnose

![image](https://user-images.githubusercontent.com/77586694/172315733-e21d53c6-70aa-438b-82ae-083087212d65.png)

![image](https://user-images.githubusercontent.com/77586694/172316034-a4389a3a-88a4-4da0-938d-a9799159f62a.png)

**Comment by nobl** [comment]
Ist bereits implementiert  (#65)  und wird mit der nächsten Version ausgerollt.
