### ISSUE TITLE
include Loq_viewer in iobroker

### ISSUE THREAD

**Issue by metzger304** [nobl/ioBroker.senec#84]
it would be nice if the log texts could be displayed in iobroker.
specifically I am looking for the battery diagnostics....

access to the log_viewer: <ip>/log.html

![image](https://user-images.githubusercontent.com/77586694/172322380-c3232a63-da0c-4931-8797-19ded94b18c9.png)

**Comment by nobl** [comment]
Ein Import der Logs ist nicht vorgesehen.

Alle interessanten Datenpunkte werden jedoch bereits jetzt schon direkt ausgelesen (Cellvoltage, Temps, ...)

Siehe auch #62 wodurch die betreffenden Werte mit hoher Priorität (mit der nächsten Version) gelesen werden.
