### ISSUE TITLE
Adapter not found

### ISSUE THREAD

**Issue by tepebox** [nobl/ioBroker.senec#9]
Hi,
trying to install your adapter.... It's not found in the admin interface and via console I get:
pi@ioBroker:~ $ iobroker install senec
host.ioBroker Unknown packetName senec
host.ioBroker download senec
File not found: senec

It shouldn't be complicated I guess ;-)

Thanks...

**Comment by nobl** [comment]
Are you using the "latest" repo in iobroker?

**Comment by tepebox** [comment]
Well, this one was way to easy ;-) Sorry, didn't know about that, I'm new to ioBroker... 

Wow, what a ton of information you provide with the adapter... Not sure if I ever get through all of that stuff... Seems to work nicely with my brand new SENEC.Home V3 hybrid duo

Thanks!
