### ISSUE TITLE
State attribute definition missing for: BMS.TF_ERROR, Val: 0

### ISSUE THREAD

**Issue by Apropo1710** [nobl/ioBroker.senec#94]
Ich nutze zur Zeit die Version 1.3.8

Ich bekomme im Log immer folgende Meldung

`<html>
<body>

senec.0 | 2022-08-08 07:09:58.429 | info | REPORT_TO_DEV: State attribute definition missing for: BMS.TF_ERROR, Val: 0
-- | -- | -- | --
senec.0 | 2022-08-08 07:09:58.015 | info | LowPrio polling ...

</body>
</html>`

Ich bin mir nicht sicher, ob es damit zu tun hat, aber Anfang letzter Woche gab es auf meinem Speicher ein Update auf die Firmware 2997. Wurde da vielleicht etwas geändert?

**Comment by nobl** [comment]
Das ist dann in der Tat ein neuer Datenpunkt, den wir bisher nicht kannten.
Die Frage ist jetzt nur: Ist es ein rein numerischer Wert oder möglicherweise eher True/False ... 

Jemand eine Idee, was "TF" in diesem Zusammenhang bedeuten könnte? (Dann könnte man direkt eine ordentliche Beschreibung mit aufnehmen)
